name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: >
          sudo apt-get update && sudo apt-get install -y nasm
          libheif-dev libheif-examples libclang-dev
          libheif-plugin-aomenc libheif-plugin-aomdec libheif-plugin-libde265
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --features asm,heic -- -D warnings
      - run: cargo test --features asm,heic

  check-macos:
    runs-on: macos-latest # Apple Silicon
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: brew install nasm
      - run: cargo test --features asm
